<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AdmContents\Teachers\StudentSelectionPage.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="AdmContents\Teachers\StudentSelectionPage.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Images\empty.jpg" />
    <None Remove="Images\emptyProfPic.png" />
    <None Remove="Images\profile_pic_example.jpg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\empty.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Firebase.js" Version="2.1.2" />
    <PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageReference Include="Microcharts" Version="0.7.1" />
    <PackageReference Include="Microcharts.Forms" Version="0.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Plugin.CloudFirestore" Version="4.1.0" />
    <PackageReference Include="Rg.Plugins.Popup" Version="1.2.0.223" />
    <PackageReference Include="Xam.Plugin.Media" Version="4.0.1.5" />
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle" Version="3.0.0.5" />
    <PackageReference Include="Xam.Plugins.Notifier" Version="3.0.1" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1687" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AdmContents\Event\EventCadastre.xaml.cs">
      <DependentUpon>EventCadastre.xaml</DependentUpon>
    </Compile>
    <Compile Update="AdmContents\Review\ResearchCadastre.xaml.cs">
      <DependentUpon>ResearchCadastre.xaml</DependentUpon>
    </Compile>
    <Compile Update="AdmContents\Teachers\TeacherCadastre.xaml.cs">
      <DependentUpon>TeacherCadastre.xaml</DependentUpon>
    </Compile>
    <Compile Update="AdmContents\Students\StudentCadastre.xaml.cs">
      <DependentUpon>StudentCadastre.xaml</DependentUpon>
    </Compile>
    <Compile Update="AdmContents\Students\StudentSelectionPage.xaml.cs">
      <DependentUpon>StudentSelectionPage.xaml</DependentUpon>
    </Compile>
    <Compile Update="StudentContents\StudentPage.xaml.cs">
      <DependentUpon>StudentPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Adm.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AdmContents\Review\ReviewDetails.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="AdmMaster.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MasterDetailPage1.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="MasterDetailPage1Master.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PopupPages\CustomPlan.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PopupPages\QuestionnairePopup.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PopupPages\ThreeButtonsDialog.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>